## YAML Template.
---
server:
     port: 9000
     
spring:
    application:
        name: API-GATEWAY
    cloud:
        gateway:
            mvc:
               routes:
                   -    id: PRODUK-SERVICE
                        uri: lb://PRODUK-SERVICE
                        predicates:
                            - Path-api/v1/produk/**
                   -    id: ORDER-SERVICE
                        uri: lb://ORDER-SERVICE
                        pradicates: 
                            - path-api/v1/order/**
                            
eureka:
    client:
        register-with-eureka: true
        fecth-registry: true
        service-url:
            defaultzone: http://localhost:8761/eureka/
        instance:
            hostname: localhost