version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: db_produk
      MYSQL_ROOT_PASSWORD: rahasia
      MYSQL_PASSWORD: rahasia
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -prahasia"]
      timeout: 20s
      retries: 10


  springboot-app:
    container_name: spring-app
    image: springboot-app
    restart: on-failure
    build: .
    ports:
      - "9001:9001"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: rahasia
      MYSQL_PORT: 3306    # we are in same network so we connect internally.
      spring.datasource.url: jdbc:mysql://mysqldb:3306/db_produk
      spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
      spring.datasource.username: root
      spring.datasource.password: rahasia
    depends_on:
      mysqldb:
        condition: service_healthy